FROM debian:latest
MAINTAINER pch18.cn

RUN apt-get update && apt-get install -y openssh-server curl wget git \
    && echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config \
    && echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config \
    && echo 'AllowTcpForwarding yes' >> /etc/ssh/sshd_config \
    && echo 'PermitTunnel yes' >> /etc/ssh/sshd_config \
    && mkdir -p /run/sshd \
    && mkdir -p /app

ENV ROOT_PASSWORD 999

EXPOSE 22

WORKDIR /app

CMD echo "root:${ROOT_PASSWORD}"|chpasswd && /usr/sbin/sshd -D


